import type { Metadata } from "next";
import "./globals.css";
import {Footer, Header, Sidebar} from "@/components";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    return (
        <html lang="ru">
        <head />
        <body>
        <Header />
        <div className="flex min-h-screen">
            <aside className="w-64">
                <Sidebar />
            </aside>
            <main className="flex-1 p-4">
                {children}
            </main>
        </div>
        <Footer />
        </body>
        </html>
    );
}
