import type { Metadata } from "next";
// import { Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { Inter } from 'next/font/google';
import styles from './page.module.css';
import {Footer, Header, Sidebar} from "@/components";
const inter = Inter({ subsets: ['latin'] });

// const geistSans = Open_Sans({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return (
  //   <html lang="en">
  //     <body className={`${geistSans.variable} ${geistMono.variable}`}>
  //       {children}
  //     </body>
  //   </html>
  // );

    return (
        <html lang="ru">
        <head />
        <body>
        <Header />
        <div className="flex min-h-screen">
            <aside className="w-64">
                <Sidebar />
            </aside>
            <main className="flex-1 p-4">
                {children}
            </main>
        </div>
        <Footer />
        </body>
        </html>
    );
}
